### ISSUE TITLE
Feature request: Monitoring

### ISSUE THREAD

**Issue by crack00r** [micahmo/WireGuardServerForWindows#31]
Is it maybe possible to minimize the normal Settings Window, but still let the Stats View open?
Right now, the "big" window cant be minimized.

Or is it maybe possible to add a Webserver with "webview" with more details?

something like this, but selfhosted.
https://www.procustodibus.com/images/blog/wireguard-monitoring/pro-custodibus-dashboard.png
https://www.procustodibus.com/images/blog/wireguard-monitoring/pro-custodibus-endpoint-history.png

**Comment by micahmo** [comment]
> Is it maybe possible to minimize the normal Settings Window, but still let the Stats View open?

Sure, this would be pretty simple to do.

> Or is it maybe possible to add a Webserver with "webview" with more details?

This would be much more advanced and probably beyond the scope of this project (at least for now). On the website you screenshotted, there is a link to a free, self-hosted WireGuard monitoring dashboard, [Wg Gen Web](https://github.com/vx3r/wg-gen-web). If you feel comfortable with Docker, you can totally run that on Windows.

I suppose there's a chance I could bundle some of that functionality into this application, as they have a pretty permissive license, but the given extensive the amount of work they've already done in that project, I'd hate to reinvent the wheel.

**Comment by micahmo** [comment]
Hey @crack00r,

The latest release ([v1.7.5](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.5)) lets you minimize (or even close) the main window while leaving the "Status" window open.

Unfortunately, at this time, I don't think I'll be able to add any kind of more fancy monitoring or statistics. This application was really just intended to be a convenient way to run various WireGuard and Windows scripts that would otherwise take a bit more work. It's not really intended to add anything on top of what you can already do in WG/Windows.

If you or someone else is able to get [Wg Gen Web](https://github.com/vx3r/wg-gen-web) talking to [WG-API](https://github.com/jamescun/wg-api) for stats on Windows, please feel free to share the setup info!
