### ISSUE TITLE
Server Setup not possible without Preshared Key

### ISSUE THREAD

**Issue by okastl** [micahmo/WireGuardServerForWindows#34]
Hi, it is my understanding, that usage of a Preshared Key in server and client configuration is optional in Wireguard.
But I can't try it, as WireGuardServerForWindows doesn't allow to setup configuration without Preshared Key.
It would be nice, if Preshared Key could be optional.

**Comment by micahmo** [comment]
Hey @okastl, thanks for bringing this up! I realized that not only should WS4W not require preshared keys (because they're optional, like you said), but the way they were configured was totally wrong.

Instead of preshared keys being something you generate once for the server and copy to all clients, they should be generated uniquely for each client, and the server should be aware of each client's PSK (if any).

This has been fixed in the latest release, [v1.7.7](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.7). I verified that upgrades from pervious versions work fine too, but for anyone who had used the previous versions and configured multiple clients, it might be a good idea to go in again and generate new PSKs for each client; otherwise, they will all be using the same one.
