### ISSUE TITLE
Server Setup not possible without generating private key

### ISSUE THREAD

**Issue by okastl** [micahmo/WireGuardServerForWindows#38]
It would be nice, if it would be possible to use an existing private key. Thank you!

**Comment by micahmo** [comment]
Thanks for the suggestion! I can't promise that I'll be able to get to these very quickly because I have limited time to work on this project.

Remember that you can always bypass WS4W and work with WireGuard directly whenever there are limitations. The server configuration file is stored at `%appdata%\WS4W\server_wg\wg_server.conf`. You can edit it manually, then sync it to WireGuard with `wg syncconf wg_server wg_server.conf`.

**Comment by micahmo** [comment]
Custom private keys can be used for server and clients in the latest release, [v1.7.8](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.8).
